from __future__ import annotations

from codex_blender_agent.tool_specs import get_dynamic_tool_specs


def test_tool_specs_expose_expected_tools():
    names = [tool["name"] for tool in get_dynamic_tool_specs()]
    expected_core_tools = [
        "list_dashboard_context",
        "list_studio_context",
        "list_ai_scope",
        "list_context_chips",
        "list_active_context_chips",
        "get_game_creator_context",
        "list_quick_prompts",
        "run_quick_prompt",
        "list_live_ai_activity",
        "run_addon_health_check",
        "list_codex_capabilities",
        "create_image_generation_brief",
        "register_generated_image_asset",
        "get_visual_review_context",
        "get_asset_intent_manifest",
        "set_asset_intent_manifest",
        "get_visual_geometry_context",
        "analyze_visual_geometry",
        "validate_gpt_asset",
        "get_asset_constraint_graph",
        "get_asset_validation_report",
        "list_asset_validation_reports",
        "get_asset_repair_plan",
        "plan_geometry_review_viewpoints",
        "get_visual_review_metrics",
        "list_visual_review_runs",
        "get_visual_review_run",
        "plan_visual_review_viewpoints",
        "apply_safe_asset_repair",
        "capture_scene_viewpoints",
        "record_visual_review_iteration",
        "create_workflow_from_intent",
        "explain_workflow_graph",
        "simplify_workflow_graph",
        "create_game_asset_plan",
        "apply_game_asset_action",
        "explain_addon_step",
        "classify_user_intent",
        "list_action_cards",
        "get_action_detail",
        "create_action_card",
        "update_action_card_plan",
        "update_action_status",
        "preview_action_card",
        "request_action_approval",
        "record_action_step",
        "record_action_warning",
        "record_action_result",
        "record_action_failure",
        "pin_output_to_thread",
        "list_blender_surfaces",
        "list_cached_operator_namespaces",
        "get_thread_context",
        "write_project_note",
        "diagnose_dashboard_workspace",
        "diagnose_ai_studio_workspace",
        "list_workflow_graphs",
        "create_workflow_graph",
        "add_workflow_node",
        "connect_workflow_nodes",
        "set_workflow_node_config",
        "inspect_workflow_graph",
        "run_workflow_graph",
        "validate_workflow_graph",
        "compile_workflow_graph",
        "preview_workflow_node",
        "preview_workflow_graph",
        "start_workflow_run",
        "resume_workflow_run",
        "stop_workflow_run",
        "list_workflow_runs",
        "get_workflow_run_detail",
        "publish_workflow_recipe",
        "list_workflow_recipes",
        "get_workflow_recipe_detail",
        "propose_workflow_patch",
        "preview_workflow_patch",
        "apply_workflow_patch",
        "register_blender_asset_library",
        "list_blender_asset_libraries",
        "search_ai_assets",
        "list_ai_asset_libraries",
        "list_asset_versions",
        "get_asset_version_detail",
        "list_asset_dependencies",
        "list_asset_provenance",
        "create_asset_publish_action",
        "promote_output_snapshot",
        "validate_asset_version",
        "publish_asset_package",
        "import_asset_package",
        "pin_asset_version",
        "fork_asset_version",
        "append_asset_version",
        "link_asset_version",
        "diagnose_ai_assets",
        "save_selection_to_asset_library",
        "append_asset_from_library",
        "get_scene_summary",
        "get_selection",
        "list_data_blocks",
        "get_object_details",
        "get_blender_property",
        "set_blender_property",
        "create_primitive",
        "create_mesh_object",
        "create_empty",
        "set_transform",
        "set_object_visibility",
        "set_parent",
        "create_vertex_group",
        "assign_vertex_group",
        "delete_object",
        "get_armature_summary",
        "set_bone_deform",
        "import_file",
        "export_fbx",
        "list_blender_operators",
        "inspect_blender_operator",
        "check_blender_operator_poll",
        "call_blender_operator",
        "execute_blender_python",
        "undo",
        "save_checkpoint_copy",
        "list_toolbox_items",
        "save_toolbox_item",
        "run_toolbox_system",
        "list_asset_items",
        "get_asset_item",
        "save_asset_file",
        "save_selected_objects_asset",
        "import_asset_item",
    ]
    for name in expected_core_tools:
        assert name in names


def test_create_primitive_schema_requires_primitive():
    tools = {tool["name"]: tool for tool in get_dynamic_tool_specs()}
    schema = tools["create_primitive"]["inputSchema"]
    assert schema["required"] == ["primitive"]
    assert "primitive" in schema["properties"]
